### ISSUE TITLE
Unable to paste text in HashTagEditableText

### ISSUE THREAD

**Issue by nivla360** [santa112358/hashtagable#11]
I was trying to paste some text but onLongPress does nothing. This would be a really convenient feature to have.

**Comment by santa112358** [comment]
@nivla360 Thank you for creating issues. I will try to update the version in order to add the features

**Comment by nivla360** [comment]
Welcome...

> @nivla360 Thank you for creating issues. I will try to update the version in order to add the features

**Comment by santa112358** [comment]
@nivla360 
Solved this in 1.0.0. 
Thank you!
