### ISSUE TITLE
Reading more and reading less functionality in HashTagText

### ISSUE THREAD

**Issue by ashishkumart** [santa112358/hashtagable#22]
Hi,

I have used this library and I would like to thank you for your effort to make my life easier 👍.

I have used this on the place of ReadMoreText widget (another library for reading more and less function) and after using HashTagText all the text is being displayed. It's not a bug actually but a feature request.

Thank You,
Ashish

**Comment by santa112358** [comment]
@ashishkumart 
Thank you for the request !!!

You mean you want to show hashtag text with `show more/show less` button, right?
If so, I will send you sample code to implement that kind of widget.

**Comment by ashishkumart** [comment]
Yes @santa112358, I want to show text that can contain hashtag along with show more/show less button.
Please share the sample code, I will try to implement that.

Thank You!

**Comment by santa112358** [comment]
@ashishkumart 
I've just created this widget and hope this will help you
https://github.com/santa112358/hashtagable_sample_read_more/blob/master/lib/hashtag_read_more_text.dart

**Comment by santa112358** [comment]
@ashishkumart 
If you have any problems with my sample code, please reopen this issue and mention me.
Now I close this. Thank you.
