### ISSUE TITLE
Feature request: @ sign detection 

### ISSUE THREAD

**Issue by SchnMar** [santa112358/hashtagable#29]
Hello @santa112358,

it would be great if hashtagable detects @ symbols too. I want to use the library in a social media like app.

Thank you!

**Comment by santa112358** [comment]
Hi @SchnMar,
Yeah, sounds nice. I will try to update the version next holidays.
Thank you.

**Comment by santa112358** [comment]
@SchnMar 
uploaded to version 1.0.2. Now you can use at sign in hashtagable.
Usage is [here](https://pub.dev/packages/hashtagable#tips)

**Comment by SchnMar** [comment]
Thank you, will check it out tomorrow!
