### ISSUE TITLE
Feature request: present preselection of possible values when # is entered

### ISSUE THREAD

**Issue by SchnMar** [santa112358/hashtagable#30]
Hello @santa112358,

another feature idea would be that people can select a hashtag from a list of values, so already used hashtags can be reused. On top of that, the list could be filtered when a user enters values after the # sign.

Thank you

**Comment by santa112358** [comment]
@SchnMar
Thank you for the requests !
I'm sorry I'm not sure if I understand what you are talking about. Is it the feature like this?
 
![IMG_0719](https://user-images.githubusercontent.com/43510799/92779705-42aa4b00-f3dd-11ea-83c4-0c48e89af4ac.PNG)

**Comment by SchnMar** [comment]
Exactly like that! I want to use it for hashtag and for at sign (#29 )

Thank you!

**Comment by santa112358** [comment]
@SchnMar 
ok, I got this. I don't think hashtagable can support all of this feature. 
The features like
- Saving the list of hashtags
- Showing the list of hashtags
should be implemented by the user of hashtagable.

What hashtagable need to do is 
Adding callback function called when users type hashtag / at sign.
Then you get the hashtag / at sign from callback and filter the list and show it.

After finishing #29, I will try to implement this feature and send you sample code.

**Comment by SchnMar** [comment]
Awesome, thank you!

**Comment by Abacaxi-Nelson** [comment]
+1 would be great !!!!!!

**Comment by santa112358** [comment]
https://github.com/santa112358/hashtagable/issues/52#issuecomment-748647085
