### ISSUE TITLE
It's not possible to use styles, e.g. GoogleFonts

### ISSUE THREAD

**Issue by 1-2-77** [santa112358/hashtagable#34]
This is not possible to use:

`style: GoogleFonts.roboto(
              fontSize: 12,
              fontWeight: FontWeight.w200,
),`

**Comment by santa112358** [comment]
@1-2-77 
Thank you for creating this issue!
`HashTagText` and `HashtagTextField` don't inherit theme textStyle, so you need to add `color: ` in your google fonts.
I guess it will solve your problem👍

**Comment by 1-2-77** [comment]
Can you please provide an example? It's not possible to use the style
parameter which is needed to implement the font.

**Comment by santa112358** [comment]
@1-2-77 
Sure, like this.
```
HashTagTextField(
  basicStyle: GoogleFonts.pacifico(
    color: Colors.black,
    fontSize: 14,
    fontWeight: FontWeight.w200,
  ),
  decoratedStyle: GoogleFonts.pacifico(
    color: Colors.red,
    fontSize: 14,
    fontWeight: FontWeight.w200,
  ),
),
```
What you have been missing is the line `color: ` in textStyle. Does it make sense?

**Comment by santa112358** [comment]
@1-2-77 
The issue looks like solved, so now I close this
