### ISSUE TITLE
How to add hint text ?

### ISSUE THREAD

**Issue by HiteshDevganiya** [santa112358/hashtagable#4]

**Comment by santa112358** [comment]
@HiteshDevganiya 
In the current version, HashtagEditableText is editableText, so it doesn't have hintText. 

If you need to use hintText now, you need to use `Stack()` whose children are `Text()` and `HashtagEditableText()`.

`Text()` has to be hidden when hashtagEditableText has content. you can listen the content of `HashtagEditableText()` in `onChanged(text){}`

I will try to update the package to add hintText next holiday, by using the method above.
Thank you for creating issue！！！

**Comment by santa112358** [comment]
@HiteshDevganiya 
I just uploaded `hashtagable 0.0.7`. In this version, you can add hintText in `HashTagEditableTextWithHIntText()`
I hope it will help you ! 
If you have any problems or questions, please feel free to ask anytime👍
