### ISSUE TITLE
suggestion  

### ISSUE THREAD

**Issue by hatemragab** [santa112358/hashtagable#41]
thanks, bro for great work! hope you to add At @ mentions detectable and links detectable

**Comment by santa112358** [comment]
@hatemragab Thank you. 
It already has the feature to detect @ in HashTagTextField and HashTagText, by adding the argument `decorateAtSign:true.` Isn't that what you mean?

**Comment by hatemragab** [comment]
Yeah 😊 what about links  detector for http:// and https://
