### ISSUE TITLE
Feature Suggestion For Getting list of all tags entered.

### ISSUE THREAD

**Issue by ch-muhammad-adil** [santa112358/hashtagable#49]
Is there any way to get list of tags ? Our system requires those tags which needs to be displayed in a separate view.

**Comment by santa112358** [comment]
@ch-muhammad-adil 
Did you try the method `extractHashTags` ? 
The one with the second plot in this section
https://pub.dev/packages/hashtagable#customize-with-useful-functions

**Comment by ch-muhammad-adil** [comment]
Ah Thank You @santa112358 , i have not seen that earlier. I have used this regular Expression, on text change. Anyhow Thank you!

          RegExp exp = new RegExp(r"\B#\w\w+");
                  exp.allMatches(value).forEach((match) {
                    listOfTagWidgets.add(
                      AlpTagsChip(title: match.group(0)),
                    );
                  });
