### ISSUE TITLE
decorateAtSign is awesome, but we need decorateYourSign

### ISSUE THREAD

**Issue by Abacaxi-Nelson** [santa112358/hashtagable#50]
Hi all,

Plugin is awesome !
For my use case, i need to decorate @ and + 
So i have to tweak plugin code:

```dart
final hashTagAtSignRegExp = RegExp(
  "(?!\\n)(?:^|\\s)([+@]([$hashTagContentLetters]+))",
  multiLine: true,
);
```

It will be awesome to have a decorateYourSign => '+@' who decorate + and @ 

Thank you,
Nelson

**Comment by santa112358** [comment]
@Abacaxi-Nelson 
Thank you for the request. 
Now I am thinking about the feature that enables developers to change the regExp for detection without tweaking the package source code.

**Comment by santa112358** [comment]
@Abacaxi-Nelson 
I published refinement of hashtagable: https://github.com/santa112358/detectable_text_field
Now you can customize regExp
