### ISSUE TITLE
extractHashTags needs decorateAtSign params

### ISSUE THREAD

**Issue by Abacaxi-Nelson** [santa112358/hashtagable#51]
hi,

Function extractHashTags should accept a decorateAtSign params.

Thx,
Nelson

**Comment by santa112358** [comment]
@Abacaxi-Nelson 
Yeah it should be. Thank you!

**Comment by santa112358** [comment]
@Abacaxi-Nelson 
I published refinement of hashtagable: https://github.com/santa112358/detectable_text_field
I think this solves your problem.
