### ISSUE TITLE
Use regular expression from argument to improve the flexibility of detection

### ISSUE THREAD

**Issue by santa112358** [santa112358/hashtagable#53]
Now hashtagable has some requests about text detection. They can be solved by fixing the regular expression inside hashtagable, but it causes another problems for other people who were ok with the previous version's regExp. 

The method I did when "decorateAtSign" feature implemented avoids the problem, which is adding the boolean argument to detect `@`, but it just gets complicated if there are many arguments like "decorate${something}".

I think using regular expression from argument is a better solution for this problem. Developers can use the regular expression set in the package, or their own one. 

If this feature is implemented, the name of the package "hashtagable" is no longer suitable for the content. There is a possibility of publishing new package for this change.

**Comment by santa112358** [comment]
https://github.com/santa112358/hashtagable/issues/50

**Comment by santa112358** [comment]
Published new package: https://github.com/santa112358/detectable_text_field

**Comment by Abacaxi-Nelson** [comment]
great job @santa112358
