### ISSUE TITLE
Support of Norwegian languages

### ISSUE THREAD

**Issue by W34therwax** [santa112358/hashtagable#59]
hello!

thanks for that awesome lib. Would it be possible to add support for Norwegian Bokmål and Nynorsk? It's a requirement for project I work on to have those two supported. Thanks in advance!
https://en.wikipedia.org/wiki/Nynorsk
https://en.wikipedia.org/wiki/Bokm%C3%A5l

**Comment by santa112358** [comment]
Hi @W34therwax, To add the language to support, we need to add new regular expression in this file: https://github.com/santa112358/hashtagable/blob/master/lib/decorator/hashtag_regular_expression.dart
You can see there are regular expressions for the languages. I am searching the regular expressions for Bokmål and Nynorsk, but I haven't found them yet.

If the languages use alphabet and there are a few original letters(like Spanish), we can support it by pasting the original letters.
example: https://github.com/santa112358/hashtagable/blob/master/lib/decorator/hashtag_regular_expression.dart#L11
If that is the case, please let me know and paste the letters here. Thank you.

**Comment by W34therwax** [comment]
hey, thanks for explaining :). So it turns out for both of those languages special letters are the same and just those:

å, ø, æ

**Comment by santa112358** [comment]
@W34therwax 
Now hashtagable v1.0.6+1 supports Norwegian Bokmål and Nynorsk🎉

Thank you.
