### ISSUE TITLE
customize regular expression.

### ISSUE THREAD

**Issue by hyobbb** [santa112358/hashtagable#68]
Hello. I would like to detect hashtags that follow without spaces.

for example, if the text is '#hash#tag#search' I would like to extract #hash, #tag, #search. Not just #hash.
so I want to delete this part of your regular expression 
(?:^|\\s) 

Is there any way to do that?

**Comment by santa112358** [comment]
@hyobbb I'm sure detectable_text_field (https://pub.dev/packages/detectable_text_field) will help you. This is the refinement of hashtagable, which allows the developers to edit regular expression. Thank you.

**Comment by hyobbb** [comment]
Thank you so much!

> @hyobbb I'm sure detectable_text_field (https://pub.dev/packages/detectable_text_field) will help you. This is the refinement of hashtagable, which allows the developers to edit regular expression.

Thank you so much!
