### ISSUE TITLE
A function that can be copied when a character is tapped

### ISSUE THREAD

**Issue by naokikotani** [santa112358/hashtagable#71]
I would like to copy text like RichText.

**Comment by santa112358** [comment]
Hi @naokikotani, thank you for the request. 
I recommend you to use `SelectableText.rich` and `getHashtagTextSpan`
```dart
SelectableText.rich(
  getHashTagTextSpan(
    decoratedStyle:
        TextStyle(fontSize: 22, color: Colors.black),
    basicStyle: TextStyle(fontSize: 22, color: Colors.blue),
    source: "#Hello World",
  ),
)
```
You can implement hashtagText with copying feature by this code. 
If you have any questions, please reopen this issue. Thank you.
