### ISSUE TITLE
Crash with Fluter 2.2.0

### ISSUE THREAD

**Issue by Urkman** [santa112358/hashtagable#86]
I get with error when trying to run an app with HashTagable:

** BUILD FAILED **
Xcode's output:
↳
    ../sdk/.pub-cache/hosted/pub.dartlang.org/hashtagable-2.0.1/lib/widgets/hashtag_text_field.dart:1422:20: Error: The getter 'scrollShortcutOverrides' isn't defined for the class '_HashTagTextFieldState'.
     - '_HashTagTextFieldState' is from 'package:hashtagable/widgets/hashtag_text_field.dart' ('../sdk/.pub-cache/hosted/pub.dartlang.org/hashtagable-2.0.1/lib/widgets/hashtag_text_field.dart').
    Try correcting the name to the name of an existing getter, or defining a getter or field named 'scrollShortcutOverrides'.
            shortcuts: scrollShortcutOverrides,
                       ^^^^^^^^^^^^^^^^^^^^^^^
    ../sdk/.pub-cache/hosted/pub.dartlang.org/hashtagable-2.0.1/lib/widgets/hashtag_editable_text.dart:218:45: Error: Required named parameter 'context' must be provided.
          return widget.controller.buildTextSpan(

**Comment by parmarravi** [comment]
I have commented the line manually as my app is running on mobile only. 
The scrollShortcutOverrides is used for web platforms.
This fixed  Gradle build for now

**Comment by santa112358** [comment]
Solved on latest version. Thank you for reporting this.
