### ISSUE TITLE
[Feature Request] Make function to extract hashtags public

### ISSUE THREAD

**Issue by SchnMar** [santa112358/hashtagable#9]
Hey,

it would be nice to have the same function available which is used to extract hash tags in the package so some additional logic can be implemented in regard of the hashtags.

Thank you!

**Comment by SchnMar** [comment]
Something like this. Maybe missing the emoji part.

```
var hashTagRegExp = RegExp(
      "(?!\\n)(?:^|\\s)(#([·・ー_ぁ-んァ-ンa-zA-Z0-9一-龠０-９ａ-ｚＡ-ＺáàãâéêíóôõúüçÁÀÃÂÉÊÍÓÔÕÚÜÇ]+))",
      multiLine: true,
    );
    final tags = hashTagRegExp.allMatches(text).toList();
    List<String> hashtags = List<String>();

    for (var tag in tags) {
      hashtags.add(
       test.substring(tag.start, tag.end),
      );
    }
```

Thank you

**Comment by santa112358** [comment]
I just updated the package and I added some functions : `bool hasHashTags(String value)` and `List<String> extractHashtags(String value)`. If they aren't what you have expected, please reopen this issue.

**Comment by santa112358** [comment]
I forgot to mention you @SchnMar . Thank you for the request!
